import streamlit as st
import random

# Setting the page layout
st.set_page_config(page_title="ナイトレイン戦技ビンゴ", layout="wide")

# Setting custom CSS (Generated by AI)
st.markdown("""
<style>
    /* Button style adjustment */
    .stButton button {
        height: 80px;  /* Reduce height slightly */
        font-weight: bold;
        font-size: 12px; /* Reduce font size slightly as skill names can be long */
        white-space: pre-wrap; /* Allow line breaks */
        padding: 5px;
        line-height: 1.2;
    }
    /* Overall padding adjustment */
    .block-container {
        padding-top: 1rem;
        padding-bottom: 2rem;
    }
    /* Reduce gap between columns */
    [data-testid="column"] {
        padding: 0 2px !important;
    }
</style>
""", unsafe_allow_html=True)

# Set data for skill lists

SKILL_LISTS = {
    "ストームルーラー": ["ストームルーラー"],
    
    "初期戦技": [
        "踏み込み(斬り上げ)", "我慢", "居合", "クイックステップ", "突撃", "嵐脚", "デターミネーション", 
        "輝剣の円陣", "グラビタス", "炎撃", "溶岩噴火", "落雷", "雷撃斬", "祈りの一撃", "毒の霧", 
        "毒蛾は二度舞う", "血の刃", "切腹", "冷気の霧", "霜踏み", "白い影の誘い", "強射", 
        "アローレイン", "バックラーパリィ", "魔力の短剣", "聖なる刃", "連続突き"
    ],
    
    "汎用戦技": [
        "踏み込み(回転薙ぎ)", "乱撃", "獅子斬り", "岩石剣", "キック", "ヒップドロップ", "地揺らし", 
        "ホーラ・ルーの地揺らし", "ウォークライ", "野蛮な咆哮", "誇示する咆哮", "トロルの咆哮", "鎖回し", 
        "回転斬り", "貫通突き", "牙突き", "二連斬り", "剣舞", "猟犬のステップ", 
        "霧の猛禽", "獣の咆哮", "構え", "回転撃", "巨人狩り", "嵐の刃", "嵐の襲撃", "嵐呼び", 
        "真空斬り", "共撃の幻", "王騎士の決意", "輝石のつぶて", "カーリアの大剣", "グレート・カーリア", 
        "回れ回れ", "ローレッタの斬撃", "暗黒波", "赤獅子の炎", "司教の突進", "黒炎の渦", "雷の羊", 
        "聖なる光輪", "聖律", "聖律共有", "黄金の地", "黄金の尻撃", "黄金樹に誓って", "無敵", "聖域",
        "血の斬撃", "血の徴収", "氷槍", "幻影の槍", "命奪拳", "暗殺の作法", "貫通射撃", 
        "連続射撃", "空撃ち", "宿し撃ち", "松明攻撃", "パリィ", "黄金パリィ", "嵐の壁", 
        "シールドバッシュ", "突撃バッシュ", "鉄壁の盾", "トープスの力場", "カーリアの返報"
    ],
    
    "固有戦技": [
        "輝石の彗礫", "レドゥビアの血刃", "黄金の刃", "死の刃", "黄金の剣技", "弔いの墓標", "眠りの霧", 
        "防ぎ得ぬ刃", "夜と炎の構え", "死蝋斬り", "ミエロスの絶叫", "オルドビスの渦", "白王の引力波", 
        "霊炎発火", "滅びの霊炎", "エオヒドの剣舞", "略奪の炎", "黄金律掲揚", "月光剣", "黄金波", 
        "狼の襲撃", "女王の黒炎", "復讐の誓い", "崩壊波", "星呼び", "運命の死", "王朝剣技", 
        "雷雲の姿", "溶岩撒き", "死のフレア", "猟犬の剣技", "黒王の斥力波", 
        "ザミェルの氷嵐", "溶岩ギロチン", "呪血の斬撃", "束の間の月影", "死屍累々", "氷雷剣", 
        "水鳥乱舞", "血刃乱舞", "雷嵐", "ローゼスの呼び声", "霊障招き", "地に伏せよ！", 
        "神託のシャボン", "流体化", "爪弾き", "百智の世界", "黄金砕き", "家族の怨霊", "星雲", 
        "降り注ぐシャボン", "噴き上がる信仰", "獣王の爪", "世界喰らい", "錫杖の魔術", 
        "黄金樹の尻撃", "神託の大シャボン", "車輪回転", "重力雷", "王の雄叫び", "聖槍の壁", 
        "槍呼びの儀", "古雷の槍", "大蛇狩り", "シルリアの渦", "狂い火突き", "血授の儀", 
        "回転斬り", "軍旗の下に", "ミケラの光輪", "天使の翼", "溶岩の海", "炎の舞", "嵐蹴撃", 
        "ご照覧あれい！", "ラダーンの驟雨", "火吹き", "眠りの炎", "毒蛇の噛みつき", 
        "黄金の返報", "伝染する怒り", "火炎舌", "炎の唾"
    ],

    "魔術": [
        "輝石のつぶて", "輝石の速つぶて", "輝石の大つぶて", "輝石の彗星", "ほうき星", "渦巻くつぶて", 
        "輝石の流星", "流星群", "輝石のアーク", "結晶連弾", "結晶散弾", "ハイマの砲丸", "ハイマの大槌", 
        "岩盤砕き", "岩盤発破", "魔力の武器", "魔力の盾", "魔術の地", "トープスの力場", "彗星アズール", 
        "滅びの流星", "創星雨", "魔術の輝剣", "輝剣の円陣", "カーリアの円陣", "巨剣陣", "降り注ぐ魔力", 
        "ローレッタの大弓", "ローレッタの絶技", "レナラの満月", "ラニの暗月", "カーリアの速剣", 
        "カーリアの大剣", "カーリアの貫き", "アデューラの月の剣", "カーリアの返報", "奇襲のつぶて", 
        "夜のつぶて", "夜の彗星", "夜巫女の霧", "永遠の暗黒", "溶岩弾", "たぎる溶岩", "ゲルミアの怒り", 
        "ライカードの怨霊", "輝石の氷塊", "氷の霧", "氷結の武器", "ザミェルの氷嵐", "砕け散る結晶", 
        "放たれる結晶", "結晶の解放", "星砕き", "岩石弾", "メテオライト", "アステール・メテオ", 
        "神託のシャボン", "神託の大シャボン", "罪の茨", "罰の茨", "怨霊呼び", "古き死の怨霊", 
        "爆ぜる霊炎", "ティビアの呼び声"
    ],

    "祈祷": [
        "性急な回復", "回復", "大回復", "王たる回復", "魔力防護", "炎防護", "雷防護", "聖防護", 
        "王たる聖防護", "拒絶", "影送り", "暗闇", "黄金樹に誓って", "黄金の魔力防護", "黄金の雷防護", 
        "黄金樹の護り", "黄金の怒り", "黄金樹の回復", "恵みの祝福", "黄金樹の恵み", "坩堝の諸相・喉袋", 
        "坩堝の諸相・尾", "坩堝の諸相・角", "エルデの流星", "黒き剣", "光輪", "三なる光輪", 
        "ラダゴンの光輪", "死を正す聖律", "聖律の剣", "不易の盾", "因果性原理", "回帰性原理", 
        "雷の槍", "雷撃", "狙いすます雷撃", "古竜の雷槍", "古竜の雷撃", "ランサクスの薙刀", 
        "フォルサクスの雷槍", "氷の雷槍", "死の雷撃", "雷の武器", "竜雷の加護", "火付け", "火よ！", 
        "火投げ", "巨人の火をくらえ", "火よ、降り注げ", "悪神の火", "火よ、迸れ", "火よ、渦巻け", 
        "火よ、焼き尽くせ！", "火の護りよ", "火よ、力を！", "火の大罪", "黒炎", "黒炎の儀式", 
        "薙ぎ払う黒炎", "黒炎の刃", "黒炎の護り", "貴種の腹芸", "獣爪", "グラングの獣爪", "獣の石", 
        "グラングの岩", "獣の生命", "蠅たかり", "血炎の爪痕", "血授", "血炎の刃", "毒霧", "毒の刃", 
        "蟲糸", "朱きエオニア", "狂い火", "堪えきれぬ狂い火", "空裂狂火", "シャブリリの叫び", "竜炎", 
        "アギールの炎", "溶岩ブレス", "テオドリックスの溶岩", "輝石ブレス", "スマラグの輝石", 
        "腐敗ブレス", "エグズキスの腐敗", "竜氷", "ボレアリスの氷霧", "プラキドサクスの滅び", 
        "竜爪", "竜咬", "グレイオールの咆哮"
    ]
}

# Set combined lists
SKILL_LISTS["魔術・祈祷"] = SKILL_LISTS["魔術"] + SKILL_LISTS["祈祷"]
SKILL_LISTS["ランダム(戦技全種)"] = SKILL_LISTS["初期戦技"] + SKILL_LISTS["汎用戦技"] + SKILL_LISTS["固有戦技"]

# Sidebar settings
st.sidebar.title("設定")

# Select grid size
grid_size = st.sidebar.selectbox("ビンゴのサイズ", [3, 5, 7], index=2)

# Area rules
zone_rules = {}

# Configure labels and default values based on grid size
if grid_size == 3:
    labels = ["中心", "外周"]
    defaults = ["ストームルーラー", "初期戦技"]
elif grid_size == 5:
    labels = ["中心", "内周", "外周"]
    defaults = ["ストームルーラー", "初期戦技", "汎用戦技"]
else: # 7
    labels = ["中心", "内周", "中周", "外周"]
    defaults = ["ストームルーラー", "初期戦技", "汎用戦技", "固有戦技"]

# Get list of keys (Adjust display order)
keys_order = ["ストームルーラー", "初期戦技", "汎用戦技", "固有戦技", "魔術", "祈祷", "魔術・祈祷", "ランダム(戦技全種)"]
# Append any keys in SKILL_LISTS 
all_keys = keys_order + [k for k in SKILL_LISTS.keys() if k not in keys_order]

#generate select boxes
for dist, label in enumerate(labels):
    num_cells = 1 if dist == 0 else 8 * dist 
    display_label = f"{label} ({num_cells}マス)"
    
    #Find the index of the default value
    default_key = defaults[dist]
    try:
        default_index = all_keys.index(default_key)
    except ValueError:
        default_index = 0

    #Create selection box
    rule = st.sidebar.selectbox(
        display_label, 
        all_keys, 
        index=default_index, 
        key=f"rule_{grid_size}_{dist}"
    )
    zone_rules[dist] = rule


#generate bingo card
def generate_bingo_card(size, rules):
    # Create blank card 
    card = [[None for _ in range(size)] for _ in range(size)]
    
    # Group coordinates 
    zones = {}
    center = (size - 1) // 2
    
    for r in range(size):
        for c in range(size):
            dist = max(abs(r - center), abs(c - center))
            if dist not in zones:
                zones[dist] = []
            zones[dist].append((r, c))
            
    # Fill cells
    for dist, coords in zones.items():
        list_name = rules[dist]
        source_list = SKILL_LISTS[list_name]
        count_needed = len(coords)
        
        # Check skills available
        if len(source_list) >= count_needed:
            selected_skills = random.sample(source_list, count_needed)
        else:
            #fill remainder with random picks
            selected_skills = source_list[:]
            remainder = count_needed - len(source_list)
            selected_skills += random.choices(source_list, k=remainder)
            random.shuffle(selected_skills)
            
        # Assign selected skills to the card grid
        for (r, c), skill in zip(coords, selected_skills):
            card[r][c] = {"name": skill, "checked": False}
            
    return card

# Main Title

st.title(f"ナイトレイン戦技ビンゴ ({grid_size}x{grid_size})")

# Detect size change
if "bingo_card" in st.session_state:
    current_card_size = len(st.session_state.bingo_card)
    if current_card_size != grid_size:
        st.session_state.bingo_card = generate_bingo_card(grid_size, zone_rules)

if "bingo_card" not in st.session_state:
    st.session_state.bingo_card = generate_bingo_card(grid_size, zone_rules)

#Reset button settings
if st.sidebar.button("ビンゴを生成/リセット", type="primary"):
    st.session_state.bingo_card = generate_bingo_card(grid_size, zone_rules)
    st.rerun()

#display the bingo card grid
for r in range(grid_size):
    cols = st.columns(grid_size)
    for c in range(grid_size):
        cell = st.session_state.bingo_card[r][c]
        
        if cell["checked"]:
            label = f"✅\n{cell['name']}"
            kind = "primary"
        else:
            label = f"\n{cell['name']}"
            kind = "secondary"

        # Create a button 
        if cols[c].button(label, key=f"btn_{r}_{c}", use_container_width=True, type=kind):
            st.session_state.bingo_card[r][c]["checked"] = not cell["checked"]
            st.rerun()

st.markdown("---")
# Convert settings
settings_str = " / ".join([f"{labels[d]}={zone_rules[d]}" for d in range(len(labels))])
st.caption(f"設定: {settings_str}")
